# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: RVCSS .NET Orchestrator

on:
  push:
    branches: [ "master", "orchestrator-mediator-worker" ]
  pull_request:
    branches: [ "master", "orchestrator-mediator-worker" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test Rvcss.Orchestrator
      run: dotnet test Rvcss.Orchestrator.Tests --no-build --verbosity normal
